services:
  - type: web
    name: fb-global-viewer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18
    region: oregon
