services:
  - type: web
    name: youtube-view-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      npm install
    startCommand: "node bot.js"
    envVars:
      - key: CHROME_BIN
        value: "/usr/bin/chromium"
