services:
  - type: worker
    name: youtube-view-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
